Fixes move action shortcuts not working
YACReader/yacreader pull request #176
Opened 2020-11-06 01:35 UTC by smalewski

Shortcuts for moving inside a page didn't work. Now they do.

2020-11-06 01:40 UTC, smalewski commented
Fixes this [issue](https://github.com/YACReader/yacreader/issues/112)

2021-01-17 09:10 UTC, luisangelsm requested changes

2021-01-17 09:10 UTC, luisangelsm commented on YACReader/viewer.cpp
> +void Viewer::moveAction(QKeySequence *key)
Did you try declaring this method as `void Viewer::moveAction(const QKeySequence &key)`? then you can invoke it as `moveAction(key)` and there is no need for indirection in the method's code. I think we can merge the PR after changing it.

2021-01-17 10:12 UTC, luisangelsm approved these changes

2021-01-17 10:45 UTC, luisangelsm commented
@smalewski thank you very much for the PR, I am merging it now.

2021-01-17 10:45 UTC, merged